/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-08-04 16:55:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AdminSideBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("jar:file:/D:/08_GIC/Java%20EE/2022_06/HealthCareSystem/WEB-INF/lib/displaytag-1.2.jar!/META-INF/displaytag.tld", Long.valueOf(1230365746000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.8.jar", Long.valueOf(1657812018750L));
    _jspx_dependants.put("jar:file:/D:/08_GIC/Java%20EE/2022_06/HealthCareSystem/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-bean.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("/WEB-INF/jsp/Common/StyleLink.jsp", Long.valueOf(1657558977833L));
    _jspx_dependants.put("/WEB-INF/lib/displaytag-1.2.jar", Long.valueOf(1657842206242L));
    _jspx_dependants.put("jar:file:/D:/08_GIC/Java%20EE/2022_06/HealthCareSystem/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-logic.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("jar:file:/D:/08_GIC/Java%20EE/2022_06/HealthCareSystem/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-html.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("/WEB-INF/jsp/Common/TagLib.jsp", Long.valueOf(1657840353014L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("<link rel=\"icon\" href=\"/HealthCareSystem/Images/hospital-regular.svg\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7a6fbe510d.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"jquery-timepicker/jquery.timepicker.min.css\">  \r\n");
      out.write("<script src=\"jquery-timepicker/jquery.timepicker.min.js\">  \r\n");
      out.write("</script> ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"col-2 bg-light pe-3 border-right\">\r\n");
      out.write("		<div class=\"sidebar pe-4 pb-3 ms-3\">\r\n");
      out.write("			<nav class=\"navbar bg-light navbar-light\">\r\n");
      out.write("				<div class=\"navbar-nav w-100\">\r\n");
      out.write("					<a href=\"AdminHome.do\" class=\"nav-item nav-link text-black\"><i\r\n");
      out.write("						class=\"fa-solid fa-house\"></i> Dashboard</a>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"nav-item dropdown\">\r\n");
      out.write("						<span class=\"nav-link dropdown-toggle text-black\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\">");
      if (_jspx_meth_logic_005fnotEmpty_005f0(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_logic_005fempty_005f0(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						<div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("							<a href=\"AddProgress.do\" class=\"dropdown-item\">");
      if (_jspx_meth_logic_005fnotEmpty_005f1(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_logic_005fempty_005f1(_jspx_page_context))
        return;
      out.write("</a> <a href=\"AdminViewProgress.do\" class=\"dropdown-item\">View\r\n");
      out.write("								Progress</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"nav-item dropdown\">\r\n");
      out.write("						<span class=\"nav-link dropdown-toggle text-black\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\">");
      if (_jspx_meth_logic_005fempty_005f2(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_logic_005fnotEmpty_005f2(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("							<a href=\"AdminAddAppointment.do\" class=\"dropdown-item\">");
      if (_jspx_meth_logic_005fempty_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_logic_005fnotEmpty_005f3(_jspx_page_context))
        return;
      out.write("</a> <a href=\"AdminViewAppointment.do\" class=\"dropdown-item\">View\r\n");
      out.write("								Appointment</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"nav-item dropdown\">\r\n");
      out.write("						<span class=\"nav-link dropdown-toggle text-black\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\"><i\r\n");
      out.write("							class=\"fa-solid fa-user-doctor\"></i> Doctor</span>\r\n");
      out.write("						<div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("							<a href=\"AddDoctor.do\" class=\"dropdown-item\">Add Doctor</a> <a\r\n");
      out.write("								href=\"ViewDoctor.do\" class=\"dropdown-item\">View Doctor </a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"nav-item dropdown\">\r\n");
      out.write("						<span class=\"nav-link dropdown-toggle text-black\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\"> ");
      if (_jspx_meth_logic_005fnotEmpty_005f4(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_logic_005fempty_005f4(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("						<div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("							<a href=\"AddPatient.do\" class=\"dropdown-item\"> ");
      if (_jspx_meth_logic_005fnotEmpty_005f5(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_logic_005fempty_005f5(_jspx_page_context))
        return;
      out.write("</a> <a href=\"AdminViewPatient.do\" class=\"dropdown-item\">View\r\n");
      out.write("								Patients </a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a href=\"Department.do\" class=\"nav-item nav-link text-black\"><i\r\n");
      out.write("						class=\"fa-solid fa-clipboard\"></i> Department</a>\r\n");
      out.write("					<div class=\"nav-item dropdown\">\r\n");
      out.write("						<span class=\"nav-link dropdown-toggle text-black\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\"><i class=\"fa-solid fa-user\"></i>\r\n");
      out.write("							Profile</span>\r\n");
      out.write("						<div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("							<a href=\"AdminProfile.do\" class=\"dropdown-item\">Your Profile</a>\r\n");
      out.write("							<a href=\"AdminChangePs.do\" class=\"dropdown-item\">Change\r\n");
      out.write("								Password</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_logic_005fnotEmpty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notEmpty
    org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f0 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
    boolean _jspx_th_logic_005fnotEmpty_005f0_reused = false;
    try {
      _jspx_th_logic_005fnotEmpty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f0.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(20,33) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f0.setProperty("reqList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(20,33) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f0.setName("PrgoressForm");
      int _jspx_eval_logic_005fnotEmpty_005f0 = _jspx_th_logic_005fnotEmpty_005f0.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<span class=\"text-danger\"><i\r\n");
          out.write("									class=\"fa-solid fa-list-check\"></i> Progress</span>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
      _jspx_th_logic_005fnotEmpty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fempty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f0 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f0_reused = false;
    try {
      _jspx_th_logic_005fempty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f0.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(24,25) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f0.setProperty("reqList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(24,25) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f0.setName("PrgoressForm");
      int _jspx_eval_logic_005fempty_005f0 = _jspx_th_logic_005fempty_005f0.doStartTag();
      if (_jspx_eval_logic_005fempty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<i class=\"fa-solid fa-list-check\"></i> Progress\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f0);
      _jspx_th_logic_005fempty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fnotEmpty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notEmpty
    org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f1 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
    boolean _jspx_th_logic_005fnotEmpty_005f1_reused = false;
    try {
      _jspx_th_logic_005fnotEmpty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f1.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(28,54) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f1.setProperty("reqList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(28,54) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f1.setName("PrgoressForm");
      int _jspx_eval_logic_005fnotEmpty_005f1 = _jspx_th_logic_005fnotEmpty_005f1.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<span class=\"text-danger\"> Add Progress</span>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f1);
      _jspx_th_logic_005fnotEmpty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f1, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fempty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f1 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f1_reused = false;
    try {
      _jspx_th_logic_005fempty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f1.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(31,26) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f1.setProperty("reqList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(31,26) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f1.setName("PrgoressForm");
      int _jspx_eval_logic_005fempty_005f1 = _jspx_th_logic_005fempty_005f1.doStartTag();
      if (_jspx_eval_logic_005fempty_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									 Add Progress\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f1);
      _jspx_th_logic_005fempty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f1, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fempty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f2 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f2_reused = false;
    try {
      _jspx_th_logic_005fempty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f2.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(39,33) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f2.setProperty("reqApptList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(39,33) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f2.setName("ProgDetailForm");
      int _jspx_eval_logic_005fempty_005f2 = _jspx_th_logic_005fempty_005f2.doStartTag();
      if (_jspx_eval_logic_005fempty_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<i class=\"fa-solid fa-calendar-check\"></i> Appointment");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f2);
      _jspx_th_logic_005fempty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f2, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fnotEmpty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notEmpty
    org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f2 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
    boolean _jspx_th_logic_005fnotEmpty_005f2_reused = false;
    try {
      _jspx_th_logic_005fnotEmpty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f2.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(41,77) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f2.setProperty("reqApptList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(41,77) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f2.setName("ProgDetailForm");
      int _jspx_eval_logic_005fnotEmpty_005f2 = _jspx_th_logic_005fnotEmpty_005f2.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<span class=\"text-danger\"><i\r\n");
          out.write("									class=\"fa-solid fa-calendar-check\"></i> Appointment</span>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f2);
      _jspx_th_logic_005fnotEmpty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f2, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fempty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f3 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f3_reused = false;
    try {
      _jspx_th_logic_005fempty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f3.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(48,62) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f3.setProperty("reqApptList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(48,62) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f3.setName("ProgDetailForm");
      int _jspx_eval_logic_005fempty_005f3 = _jspx_th_logic_005fempty_005f3.doStartTag();
      if (_jspx_eval_logic_005fempty_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("Add Appointment");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f3);
      _jspx_th_logic_005fempty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f3, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fnotEmpty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notEmpty
    org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f3 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
    boolean _jspx_th_logic_005fnotEmpty_005f3_reused = false;
    try {
      _jspx_th_logic_005fnotEmpty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f3.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(50,8) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f3.setProperty("reqApptList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(50,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f3.setName("ProgDetailForm");
      int _jspx_eval_logic_005fnotEmpty_005f3 = _jspx_th_logic_005fnotEmpty_005f3.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<span class=\"text-danger\">Add Appointment</span>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f3);
      _jspx_th_logic_005fnotEmpty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f3, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fnotEmpty_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notEmpty
    org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f4 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
    boolean _jspx_th_logic_005fnotEmpty_005f4_reused = false;
    try {
      _jspx_th_logic_005fnotEmpty_005f4.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f4.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(68,34) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f4.setProperty("reqPatientList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(68,34) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f4.setName("PatientForm");
      int _jspx_eval_logic_005fnotEmpty_005f4 = _jspx_th_logic_005fnotEmpty_005f4.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<span class=\"text-danger\"><i class=\"fa-solid fa-user\"></i>\r\n");
          out.write("									Patient</span>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f4);
      _jspx_th_logic_005fnotEmpty_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f4, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fempty_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f4 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f4_reused = false;
    try {
      _jspx_th_logic_005fempty_005f4.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f4.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(72,25) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f4.setProperty("reqPatientList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(72,25) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f4.setName("PatientForm");
      int _jspx_eval_logic_005fempty_005f4 = _jspx_th_logic_005fempty_005f4.doStartTag();
      if (_jspx_eval_logic_005fempty_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<i class=\"fa-solid fa-user\"></i>\r\n");
          out.write("									Patient\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f4);
      _jspx_th_logic_005fempty_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f4, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fnotEmpty_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notEmpty
    org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f5 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
    boolean _jspx_th_logic_005fnotEmpty_005f5_reused = false;
    try {
      _jspx_th_logic_005fnotEmpty_005f5.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f5.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(77,54) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f5.setProperty("reqPatientList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(77,54) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f5.setName("PatientForm");
      int _jspx_eval_logic_005fnotEmpty_005f5 = _jspx_th_logic_005fnotEmpty_005f5.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<span class=\"text-danger\">Add Patients</span>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f5);
      _jspx_th_logic_005fnotEmpty_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f5, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fempty_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:empty
    org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f5 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
    boolean _jspx_th_logic_005fempty_005f5_reused = false;
    try {
      _jspx_th_logic_005fempty_005f5.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fempty_005f5.setParent(null);
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(80,26) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f5.setProperty("reqPatientList");
      // /WEB-INF/jsp/Admin/AdminSideBar.jsp(80,26) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fempty_005f5.setName("PatientForm");
      int _jspx_eval_logic_005fempty_005f5 = _jspx_th_logic_005fempty_005f5.doStartTag();
      if (_jspx_eval_logic_005fempty_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									Add Patients\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_logic_005fempty_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fempty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f5);
      _jspx_th_logic_005fempty_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f5, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f5_reused);
    }
    return false;
  }
}
