package com.HealthCareSystem.business.entity;
// Generated Jul 23, 2022, 6:48:25 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String adminLoginName;
	private String password;
	private String adminName;
	private String gender;
	private Date dateOfBirth;
	private String mail;
	private String phone;
	private String bloodType;
	private String address;

	public Admin() {
	}

	public Admin(String adminLoginName, String password, String adminName, String gender, Date dateOfBirth, String mail,
			String phone, String bloodType, String address) {
		this.adminLoginName = adminLoginName;
		this.password = password;
		this.adminName = adminName;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.mail = mail;
		this.phone = phone;
		this.bloodType = bloodType;
		this.address = address;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminLoginName() {
		return this.adminLoginName;
	}

	public void setAdminLoginName(String adminLoginName) {
		this.adminLoginName = adminLoginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
