package com.HealthCareSystem.business.entity;
// Generated Jul 23, 2022, 6:48:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer departmentId;
	private String departmentName;
	private String departmentDescription;
	private String status;
	private int noOfDoctor;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);

	public Department() {
	}

	public Department(String departmentName, String departmentDescription, String status) {
		this.departmentName = departmentName;
		this.departmentDescription = departmentDescription;
		this.status = status;
	}

	public Department(String departmentName, String departmentDescription, String status, Set<Doctor> doctors) {
		this.departmentName = departmentName;
		this.departmentDescription = departmentDescription;
		this.status = status;
		this.doctors = doctors;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getDepartmentDescription() {
		return this.departmentDescription;
	}

	public void setDepartmentDescription(String departmentDescription) {
		this.departmentDescription = departmentDescription;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getNoOfDoctor() {
		return noOfDoctor;
	}

	public void setNoOfDoctor(int noOfDoctor) {
		this.noOfDoctor = noOfDoctor;
	}

	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

}
