package com.HealthCareSystem.business.entity;
// Generated Jul 23, 2022, 6:48:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * PatientProgress generated by hbm2java
 */
public class PatientProgress implements java.io.Serializable {

	private Integer progressId;
	private Doctor doctor;
	private Patient patient;
	private String diseaseName;
	private String symptoms;
	private String status;
	private Set<ProgressDetail> progressDetails = new HashSet<ProgressDetail>(0);

	public PatientProgress() {
	}

	public PatientProgress(Doctor doctor, Patient patient, String symptoms) {
		this.doctor = doctor;
		this.patient = patient;
		this.symptoms = symptoms;
	}

	public PatientProgress(Doctor doctor, Patient patient, String diseaseName, String symptoms,
			Set<ProgressDetail> progressDetails,String status) {
		this.doctor = doctor;
		this.patient = patient;
		this.diseaseName = diseaseName;
		this.symptoms = symptoms;
		this.progressDetails = progressDetails;
		this.status=status;
	}

	public Integer getProgressId() {
		return this.progressId;
	}

	public void setProgressId(Integer progressId) {
		this.progressId = progressId;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public String getDiseaseName() {
		return this.diseaseName;
	}

	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	public String getSymptoms() {
		return this.symptoms;
	}

	public void setSymptoms(String symptoms) {
		this.symptoms = symptoms;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<ProgressDetail> getProgressDetails() {
		return this.progressDetails;
	}

	public void setProgressDetails(Set<ProgressDetail> progressDetails) {
		this.progressDetails = progressDetails;
	}

}
