/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-10 07:29:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.Patient;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Progress_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("jar:file:/D:/Training/J2EE/HealthCareSystem/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-logic.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.8.jar", Long.valueOf(1657812018750L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1657812018744L));
    _jspx_dependants.put("/WEB-INF/jsp/Common/StyleLink.jsp", Long.valueOf(1665242462116L));
    _jspx_dependants.put("/WEB-INF/jsp/Patient/PatientSideBar.jsp", Long.valueOf(1665149010436L));
    _jspx_dependants.put("/WEB-INF/lib/displaytag-1.2.jar", Long.valueOf(1657842206242L));
    _jspx_dependants.put("jar:file:/D:/Training/J2EE/HealthCareSystem/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098687690000L));
    _jspx_dependants.put("jar:file:/D:/Training/J2EE/HealthCareSystem/WEB-INF/lib/displaytag-1.2.jar!/META-INF/displaytag.tld", Long.valueOf(1230365746000L));
    _jspx_dependants.put("/WEB-INF/jsp/Common/TagLib.jsp", Long.valueOf(1663398602553L));
    _jspx_dependants.put("jar:file:/D:/Training/J2EE/HealthCareSystem/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-html.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("jar:file:/D:/Training/J2EE/HealthCareSystem/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-bean.tld", Long.valueOf(1172892492000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleClass_005fstyle_005fproperty_005fdisabled_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005ftextarea_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleClass_005fstyle_005fproperty_005fdisabled_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005ftextarea_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass.release();
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody.release();
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.release();
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.release();
    _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleClass_005fstyle_005fproperty_005fdisabled_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005ftextarea_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/HealthCareSystem/Images/hospital-regular.svg\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7a6fbe510d.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Medical Record</title>\r\n");
      out.write("<style>\r\n");
      out.write("label.error {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"gradient-skyblue\">\r\n");
      out.write("	<div class=\"container-fluid overflow-hidden\">\r\n");
      out.write("		<div class=\"row vh-100 overflow-auto\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/HealthCareSystem/Images/hospital-regular.svg\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/7a6fbe510d.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-white\">\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-white d-flex sticky-top\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white\">\r\n");
      out.write("			<a href=\"#\"\r\n");
      out.write("				class=\"d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-black text-decoration-none\">\r\n");
      out.write("				<span class=\"fs-5 d-none d-md-inline text-primary\">Welcome,<br>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PatientForm.loginPatient.patientName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<ul\r\n");
      out.write("				class=\"nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start\"\r\n");
      out.write("				id=\"menu\">\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"PatientHome.do\"\r\n");
      out.write("					class=\"nav-link px-sm-0 px-2\"><i class=\"fa-solid fa-house\"></i><span\r\n");
      out.write("						class=\"ms-1 d-none d-sm-inline\">Home</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"Progress.do\"\r\n");
      out.write("					class=\"nav-link px-sm-0 px-2\"><i class=\"fa-solid fa-list-check\"></i><span\r\n");
      out.write("						class=\"ms-1 d-none d-sm-inline\">Medical Record</span></a></li>\r\n");
      out.write("				<li><a href=\"Appointment.do\" class=\"nav-link px-sm-0 px-2\"><i\r\n");
      out.write("						class=\"fa-solid fa-calendar-check\"></i><span\r\n");
      out.write("						class=\"ms-1 d-none d-sm-inline\">Appointment</span> </a></li>\r\n");
      out.write("				<li><a href=\"PatientSearchDoctor.do\"\r\n");
      out.write("					class=\"nav-link px-sm-0 px-2\"><i\r\n");
      out.write("						class=\"fa-solid fa-user-doctor\"></i><span\r\n");
      out.write("						class=\"ms-1 d-none d-sm-inline\">Search Doctor</span> </a></li>\r\n");
      out.write("				<li class=\"dropdown\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link dropdown-toggle px-sm-0 px-1\" id=\"dropdown\"\r\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("						class=\"fa-solid fa-user-tie\"></i><span\r\n");
      out.write("						class=\"ms-1 d-none d-sm-inline\">Profile</span>\r\n");
      out.write("				</a>\r\n");
      out.write("					<ul class=\"dropdown-menu dropdown-menu-dark text-small shadow\"\r\n");
      out.write("						aria-labelledby=\"dropdown\">\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"PatientProfile.do\">Your\r\n");
      out.write("								Profile</a></li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"PatientChangePs.do\">Change\r\n");
      out.write("								Password</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<hr class=\"dropdown-divider\">\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"logout.do\"><i\r\n");
      out.write("								class=\"fa-solid fa-arrow-right-from-bracket\"></i>Logout</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("			<div class=\"col d-flex flex-column h-sm-100 gradient-skyblue\">\r\n");
      out.write("				<main class=\"row overflow-auto\">\r\n");
      out.write("					<div class=\"col pt-4 \">\r\n");
      out.write("						<!-- header -->\r\n");
      out.write("						<h2 class=\"mt-2 text-center\">Medical Record</h2>\r\n");
      out.write("						<!--end header -->\r\n");
      out.write("						<hr>\r\n");
      out.write("						<div class=\"container \">\r\n");
      out.write("							<!-- menu tab -->\r\n");
      out.write("							<ul class=\"nav nav-tabs\" id=\"myTab\">\r\n");
      out.write("								<!-- during treatment tab menu -->\r\n");
      out.write("								<li class=\"nav-item\"><a href=\"#still\"\r\n");
      out.write("									class=\"nav-link ");
if (session.getAttribute("patientProg").equals("start"))
	out.write("active");
      out.write("\"\r\n");
      out.write("									data-bs-toggle=\"tab\">During Treatment<span\r\n");
      out.write("										class=\"ms-1  badge bg-success\r\n");
      out.write("rounded-pill float-end\">\r\n");
      out.write("											");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PatientProgress.progList.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<!--end of during treatment tab menu -->\r\n");
      out.write("								<!--  treatment done tab menu -->\r\n");
      out.write("								<li class=\"nav-item\"><a href=\"#done\" class=\"nav-link\"\r\n");
      out.write("									data-bs-toggle=\"tab\">Treatment Done <span\r\n");
      out.write("										class=\"ms-1  badge bg-secondary\r\n");
      out.write("rounded-pill float-end\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PatientProgress.doneList.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<!-- end of treatment done tab menu -->\r\n");
      out.write("								<!--  request progress tab menu -->\r\n");
      out.write("								");

								if (session.getAttribute("patientProg").equals("req")) {
								
      out.write("\r\n");
      out.write("								<li class=\"nav-item \"><a href=\"#request\"\r\n");
      out.write("									class=\"nav-link active\" data-bs-toggle=\"tab\">Request\r\n");
      out.write("										Progress </a></li>\r\n");
      out.write("								");

								}
								
      out.write("<!-- end of request progress tab menu -->\r\n");
      out.write("							</ul>\r\n");
      out.write("							<!-- menu tab end -->\r\n");
      out.write("							<div class=\"tab-content\">\r\n");
      out.write("								<!-- during treatment menu content  -->\r\n");
      out.write("								<div\r\n");
      out.write("									class=\"tab-pane fade");
if (session.getAttribute("patientProg").equals("start"))
	out.write("show active");
      out.write("\"\r\n");
      out.write("									id=\"still\">\r\n");
      out.write("									<div class=\"row mt-3\">\r\n");
      out.write("										");

										int i = 1;
										
      out.write("\r\n");
      out.write("										");
      //  display:table
      org.displaytag.tags.TableTag _jspx_th_display_005ftable_005f0 = (org.displaytag.tags.TableTag) _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass.get(org.displaytag.tags.TableTag.class);
      boolean _jspx_th_display_005ftable_005f0_reused = false;
      try {
        _jspx_th_display_005ftable_005f0.setPageContext(_jspx_page_context);
        _jspx_th_display_005ftable_005f0.setParent(null);
        // /WEB-INF/jsp/Patient/Progress.jsp(69,10) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f0.setUid("data");
        // /WEB-INF/jsp/Patient/Progress.jsp(69,10) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f0.setName("sessionScope.PatientProgress.progList");
        // /WEB-INF/jsp/Patient/Progress.jsp(69,10) name = pagesize type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f0.setPagesize(9);
        // /WEB-INF/jsp/Patient/Progress.jsp(69,10) name = requestURI type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f0.setRequestURI("Progress.do");
        // /WEB-INF/jsp/Patient/Progress.jsp(69,10) name = class type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f0.setClass("table table-striped bg-white my-custom-scrollbar table-wrapper-scroll-y");
        int _jspx_eval_display_005ftable_005f0 = _jspx_th_display_005ftable_005f0.doStartTag();
        if (_jspx_eval_display_005ftable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          java.lang.Object data = null;
          java.lang.Integer data_rowNum = null;
          if (_jspx_eval_display_005ftable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_display_005ftable_005f0);
          }
          data = (java.lang.Object) _jspx_page_context.findAttribute("data");
          data_rowNum = (java.lang.Integer) _jspx_page_context.findAttribute("data_rowNum");
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("											");
            //  display:column
            org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f0 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody.get(org.displaytag.tags.ColumnTag.class);
            boolean _jspx_th_display_005fcolumn_005f0_reused = false;
            try {
              _jspx_th_display_005fcolumn_005f0.setPageContext(_jspx_page_context);
              _jspx_th_display_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
              // /WEB-INF/jsp/Patient/Progress.jsp(74,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_display_005fcolumn_005f0.setTitle("No");
              // /WEB-INF/jsp/Patient/Progress.jsp(74,11) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_display_005fcolumn_005f0.setValue(i++);
              int _jspx_eval_display_005fcolumn_005f0 = _jspx_th_display_005fcolumn_005f0.doStartTag();
              if (_jspx_th_display_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody.reuse(_jspx_th_display_005fcolumn_005f0);
              _jspx_th_display_005fcolumn_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f0, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f0_reused);
            }
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f1(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f2(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f3(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f4(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f0(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f1(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f2(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f3(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f4(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f5(_jspx_th_display_005ftable_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_display_005ftable_005f0.doAfterBody();
            data = (java.lang.Object) _jspx_page_context.findAttribute("data");
            data_rowNum = (java.lang.Integer) _jspx_page_context.findAttribute("data_rowNum");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_display_005ftable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_display_005ftable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass.reuse(_jspx_th_display_005ftable_005f0);
        _jspx_th_display_005ftable_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005ftable_005f0, _jsp_getInstanceManager(), _jspx_th_display_005ftable_005f0_reused);
      }
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!--end of  during treatment menu content  -->\r\n");
      out.write("								<!--  treatment done menu content  -->\r\n");
      out.write("								<div class=\"tab-pane fade\" id=\"done\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"row mt-3\">\r\n");
      out.write("										");

										int j = 1;
										
      out.write("\r\n");
      out.write("										");
      //  display:table
      org.displaytag.tags.TableTag _jspx_th_display_005ftable_005f1 = (org.displaytag.tags.TableTag) _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass.get(org.displaytag.tags.TableTag.class);
      boolean _jspx_th_display_005ftable_005f1_reused = false;
      try {
        _jspx_th_display_005ftable_005f1.setPageContext(_jspx_page_context);
        _jspx_th_display_005ftable_005f1.setParent(null);
        // /WEB-INF/jsp/Patient/Progress.jsp(109,10) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f1.setUid("data");
        // /WEB-INF/jsp/Patient/Progress.jsp(109,10) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f1.setName("sessionScope.PatientProgress.doneList");
        // /WEB-INF/jsp/Patient/Progress.jsp(109,10) name = pagesize type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f1.setPagesize(9);
        // /WEB-INF/jsp/Patient/Progress.jsp(109,10) name = requestURI type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f1.setRequestURI("Progress.do");
        // /WEB-INF/jsp/Patient/Progress.jsp(109,10) name = class type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_display_005ftable_005f1.setClass("table table-striped bg-white my-custom-scrollbar table-wrapper-scroll-y");
        int _jspx_eval_display_005ftable_005f1 = _jspx_th_display_005ftable_005f1.doStartTag();
        if (_jspx_eval_display_005ftable_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          java.lang.Object data = null;
          java.lang.Integer data_rowNum = null;
          if (_jspx_eval_display_005ftable_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_display_005ftable_005f1);
          }
          data = (java.lang.Object) _jspx_page_context.findAttribute("data");
          data_rowNum = (java.lang.Integer) _jspx_page_context.findAttribute("data_rowNum");
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("											");
            //  display:column
            org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f5 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody.get(org.displaytag.tags.ColumnTag.class);
            boolean _jspx_th_display_005fcolumn_005f5_reused = false;
            try {
              _jspx_th_display_005fcolumn_005f5.setPageContext(_jspx_page_context);
              _jspx_th_display_005fcolumn_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
              // /WEB-INF/jsp/Patient/Progress.jsp(114,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_display_005fcolumn_005f5.setTitle("No");
              // /WEB-INF/jsp/Patient/Progress.jsp(114,11) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_display_005fcolumn_005f5.setValue(j++);
              int _jspx_eval_display_005fcolumn_005f5 = _jspx_th_display_005fcolumn_005f5.doStartTag();
              if (_jspx_th_display_005fcolumn_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005fvalue_005ftitle_005fnobody.reuse(_jspx_th_display_005fcolumn_005f5);
              _jspx_th_display_005fcolumn_005f5_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f5, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f5_reused);
            }
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f6(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f7(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fcolumn_005f8(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f6(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f7(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f8(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f9(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f10(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_display_005fsetProperty_005f11(_jspx_th_display_005ftable_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_display_005ftable_005f1.doAfterBody();
            data = (java.lang.Object) _jspx_page_context.findAttribute("data");
            data_rowNum = (java.lang.Integer) _jspx_page_context.findAttribute("data_rowNum");
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_display_005ftable_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_display_005ftable_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005frequestURI_005fpagesize_005fname_005fid_005fclass.reuse(_jspx_th_display_005ftable_005f1);
        _jspx_th_display_005ftable_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005ftable_005f1, _jsp_getInstanceManager(), _jspx_th_display_005ftable_005f1_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!--end  treatment done menu content  -->\r\n");
      out.write("								<!--  request progress menu content  -->\r\n");
      out.write("								");

								if (session.getAttribute("patientProg").equals("req")) {
								
      if (_jspx_meth_html_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");

								}
								
      out.write("<!--end  request progress menu content  -->\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Content -->\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</main>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Main (Nav & Content) -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.js\"></script>\r\n");
      out.write("	<script src=\"/HealthCareSystem/js/Patient/Progress.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_display_005fcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f1 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f1_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f1.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(75,11) name = property type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f1.setProperty("doctor.doctorName");
      // /WEB-INF/jsp/Patient/Progress.jsp(75,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f1.setTitle("Doctor Name");
      int _jspx_eval_display_005fcolumn_005f1 = _jspx_th_display_005fcolumn_005f1.doStartTag();
      if (_jspx_th_display_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.reuse(_jspx_th_display_005fcolumn_005f1);
      _jspx_th_display_005fcolumn_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f1, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fcolumn_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f2 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f2_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f2.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(77,11) name = property type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f2.setProperty("diseaseName");
      // /WEB-INF/jsp/Patient/Progress.jsp(77,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f2.setTitle("Disease Name");
      int _jspx_eval_display_005fcolumn_005f2 = _jspx_th_display_005fcolumn_005f2.doStartTag();
      if (_jspx_th_display_005fcolumn_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.reuse(_jspx_th_display_005fcolumn_005f2);
      _jspx_th_display_005fcolumn_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f2, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fcolumn_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f3 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f3_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f3.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(78,11) name = paramId type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f3.setParamId("progressid");
      // /WEB-INF/jsp/Patient/Progress.jsp(78,11) name = paramProperty type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f3.setParamProperty("progressId");
      // /WEB-INF/jsp/Patient/Progress.jsp(78,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f3.setTitle("View");
      // /WEB-INF/jsp/Patient/Progress.jsp(78,11) name = href type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f3.setHref("ViewProgressDetail.do?path=patient");
      int _jspx_eval_display_005fcolumn_005f3 = _jspx_th_display_005fcolumn_005f3.doStartTag();
      if (_jspx_eval_display_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_display_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_display_005fcolumn_005f3);
        }
        do {
          out.write("\r\n");
          out.write("												<i class=\"fa-regular fa-eye\"></i> Detail\r\n");
          out.write("																");
          int evalDoAfterBody = _jspx_th_display_005fcolumn_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_display_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_display_005fcolumn_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.reuse(_jspx_th_display_005fcolumn_005f3);
      _jspx_th_display_005fcolumn_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f3, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fcolumn_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f4 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f4_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f4.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(83,11) name = paramId type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f4.setParamId("progressid");
      // /WEB-INF/jsp/Patient/Progress.jsp(83,11) name = paramProperty type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f4.setParamProperty("progressId");
      // /WEB-INF/jsp/Patient/Progress.jsp(83,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f4.setTitle("Request");
      // /WEB-INF/jsp/Patient/Progress.jsp(83,11) name = href type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f4.setHref("Appointment.do");
      int _jspx_eval_display_005fcolumn_005f4 = _jspx_th_display_005fcolumn_005f4.doStartTag();
      if (_jspx_eval_display_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_display_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_display_005fcolumn_005f4);
        }
        do {
          out.write("\r\n");
          out.write("												<i class=\"fa-solid fa-square-plus\"></i> appointment\r\n");
          out.write("																");
          int evalDoAfterBody = _jspx_th_display_005fcolumn_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_display_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_display_005fcolumn_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.reuse(_jspx_th_display_005fcolumn_005f4);
      _jspx_th_display_005fcolumn_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f4, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f0 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f0_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(88,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f0.setName("paging.banner.placement");
      // /WEB-INF/jsp/Patient/Progress.jsp(88,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f0.setValue("bottom");
      int _jspx_eval_display_005fsetProperty_005f0 = _jspx_th_display_005fsetProperty_005f0.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f0);
      _jspx_th_display_005fsetProperty_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f0, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f1 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f1_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f1.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(90,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f1.setName("paging.banner.some_items_found");
      // /WEB-INF/jsp/Patient/Progress.jsp(90,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f1.setValue("");
      int _jspx_eval_display_005fsetProperty_005f1 = _jspx_th_display_005fsetProperty_005f1.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f1);
      _jspx_th_display_005fsetProperty_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f1, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f2 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f2_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f2.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(92,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f2.setName("paging.banner.all_items_found");
      // /WEB-INF/jsp/Patient/Progress.jsp(92,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f2.setValue("");
      int _jspx_eval_display_005fsetProperty_005f2 = _jspx_th_display_005fsetProperty_005f2.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f2);
      _jspx_th_display_005fsetProperty_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f2, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f3 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f3_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f3.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(94,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f3.setName("paging.banner.one_item_found");
      // /WEB-INF/jsp/Patient/Progress.jsp(94,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f3.setValue("");
      int _jspx_eval_display_005fsetProperty_005f3 = _jspx_th_display_005fsetProperty_005f3.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f3);
      _jspx_th_display_005fsetProperty_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f3, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f4 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f4_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f4.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(96,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f4.setName("paging.banner.onepage");
      // /WEB-INF/jsp/Patient/Progress.jsp(96,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f4.setValue("");
      int _jspx_eval_display_005fsetProperty_005f4 = _jspx_th_display_005fsetProperty_005f4.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f4);
      _jspx_th_display_005fsetProperty_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f4, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f5 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f5_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f5.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(97,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f5.setName("basic.msg.empty_list");
      // /WEB-INF/jsp/Patient/Progress.jsp(97,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f5.setValue("");
      int _jspx_eval_display_005fsetProperty_005f5 = _jspx_th_display_005fsetProperty_005f5.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f5);
      _jspx_th_display_005fsetProperty_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f5, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fcolumn_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f6 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f6_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f6.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(115,11) name = property type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f6.setProperty("doctor.doctorName");
      // /WEB-INF/jsp/Patient/Progress.jsp(115,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f6.setTitle("Doctor Name");
      int _jspx_eval_display_005fcolumn_005f6 = _jspx_th_display_005fcolumn_005f6.doStartTag();
      if (_jspx_th_display_005fcolumn_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.reuse(_jspx_th_display_005fcolumn_005f6);
      _jspx_th_display_005fcolumn_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f6, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fcolumn_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f7 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f7_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f7.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(117,11) name = property type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f7.setProperty("diseaseName");
      // /WEB-INF/jsp/Patient/Progress.jsp(117,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f7.setTitle("Disease Name");
      int _jspx_eval_display_005fcolumn_005f7 = _jspx_th_display_005fcolumn_005f7.doStartTag();
      if (_jspx_th_display_005fcolumn_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fproperty_005fnobody.reuse(_jspx_th_display_005fcolumn_005f7);
      _jspx_th_display_005fcolumn_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f7, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fcolumn_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:column
    org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f8 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.get(org.displaytag.tags.ColumnTag.class);
    boolean _jspx_th_display_005fcolumn_005f8_reused = false;
    try {
      _jspx_th_display_005fcolumn_005f8.setPageContext(_jspx_page_context);
      _jspx_th_display_005fcolumn_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(118,11) name = paramId type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f8.setParamId("progressid");
      // /WEB-INF/jsp/Patient/Progress.jsp(118,11) name = paramProperty type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f8.setParamProperty("progressId");
      // /WEB-INF/jsp/Patient/Progress.jsp(118,11) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f8.setTitle("View");
      // /WEB-INF/jsp/Patient/Progress.jsp(118,11) name = href type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fcolumn_005f8.setHref("ViewProgressDetail.do?path=patient");
      int _jspx_eval_display_005fcolumn_005f8 = _jspx_th_display_005fcolumn_005f8.doStartTag();
      if (_jspx_eval_display_005fcolumn_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_display_005fcolumn_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_display_005fcolumn_005f8);
        }
        do {
          out.write("\r\n");
          out.write("												<i class=\"fa-regular fa-eye\"></i> Detail\r\n");
          out.write("																");
          int evalDoAfterBody = _jspx_th_display_005fcolumn_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_display_005fcolumn_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_display_005fcolumn_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fparamProperty_005fparamId_005fhref.reuse(_jspx_th_display_005fcolumn_005f8);
      _jspx_th_display_005fcolumn_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fcolumn_005f8, _jsp_getInstanceManager(), _jspx_th_display_005fcolumn_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f6 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f6_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f6.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(124,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f6.setName("paging.banner.placement");
      // /WEB-INF/jsp/Patient/Progress.jsp(124,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f6.setValue("bottom");
      int _jspx_eval_display_005fsetProperty_005f6 = _jspx_th_display_005fsetProperty_005f6.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f6);
      _jspx_th_display_005fsetProperty_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f6, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f7 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f7_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f7.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(126,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f7.setName("paging.banner.some_items_found");
      // /WEB-INF/jsp/Patient/Progress.jsp(126,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f7.setValue("");
      int _jspx_eval_display_005fsetProperty_005f7 = _jspx_th_display_005fsetProperty_005f7.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f7);
      _jspx_th_display_005fsetProperty_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f7, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f8 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f8_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f8.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(128,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f8.setName("paging.banner.all_items_found");
      // /WEB-INF/jsp/Patient/Progress.jsp(128,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f8.setValue("");
      int _jspx_eval_display_005fsetProperty_005f8 = _jspx_th_display_005fsetProperty_005f8.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f8);
      _jspx_th_display_005fsetProperty_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f8, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f9 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f9_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f9.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(130,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f9.setName("paging.banner.one_item_found");
      // /WEB-INF/jsp/Patient/Progress.jsp(130,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f9.setValue("");
      int _jspx_eval_display_005fsetProperty_005f9 = _jspx_th_display_005fsetProperty_005f9.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f9);
      _jspx_th_display_005fsetProperty_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f9, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f10 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f10_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f10.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(132,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f10.setName("paging.banner.onepage");
      // /WEB-INF/jsp/Patient/Progress.jsp(132,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f10.setValue("");
      int _jspx_eval_display_005fsetProperty_005f10 = _jspx_th_display_005fsetProperty_005f10.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f10);
      _jspx_th_display_005fsetProperty_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f10, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f11 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    boolean _jspx_th_display_005fsetProperty_005f11_reused = false;
    try {
      _jspx_th_display_005fsetProperty_005f11.setPageContext(_jspx_page_context);
      _jspx_th_display_005fsetProperty_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f1);
      // /WEB-INF/jsp/Patient/Progress.jsp(133,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f11.setName("basic.msg.empty_list");
      // /WEB-INF/jsp/Patient/Progress.jsp(133,11) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005fsetProperty_005f11.setValue("No Progress Found!");
      int _jspx_eval_display_005fsetProperty_005f11 = _jspx_th_display_005fsetProperty_005f11.doStartTag();
      if (_jspx_th_display_005fsetProperty_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f11);
      _jspx_th_display_005fsetProperty_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_display_005fsetProperty_005f11, _jsp_getInstanceManager(), _jspx_th_display_005fsetProperty_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:form
    org.apache.struts.taglib.html.FormTag _jspx_th_html_005fform_005f0 = (org.apache.struts.taglib.html.FormTag) _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.get(org.apache.struts.taglib.html.FormTag.class);
    boolean _jspx_th_html_005fform_005f0_reused = false;
    try {
      _jspx_th_html_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/Patient/Progress.jsp(143,10) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setAction("/Progress");
      // /WEB-INF/jsp/Patient/Progress.jsp(143,10) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005fform_005f0.setStyleId("myForm");
      int _jspx_eval_html_005fform_005f0 = _jspx_th_html_005fform_005f0.doStartTag();
      if (_jspx_eval_html_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<div class=\"tab-pane fade show active text-center\" id=\"request\">\r\n");
          out.write("										<div class=\"form-group row mt-3\">\r\n");
          out.write("											<label class=\"col-md-2 col-form-label col-sm-6 col-lg-2\"><span\r\n");
          out.write("												class=\"h5\">Doctor Name</span></label>\r\n");
          out.write("											<div class=\"col-md-3 col-sm-6 col-lg-3\">\r\n");
          out.write("												");
          if (_jspx_meth_html_005ftext_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("											</div>\r\n");
          out.write("											<label class=\"col-md-2 col-sm-6 col-lg-2 col-form-label\"><span\r\n");
          out.write("												class=\"h5\">Symptoms</span></label>\r\n");
          out.write("											<div class=\"col-md-3 col-sm-6 col-lg-3\" style=\"height: 150px\">\r\n");
          out.write("												");
          if (_jspx_meth_html_005ftextarea_005f0(_jspx_th_html_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("											</div>\r\n");
          out.write("										</div>\r\n");
          out.write("\r\n");
          out.write("										<button name=\"request\" type=\"submit\"\r\n");
          out.write("											class=\"btn btn-outline-primary\">Request</button>\r\n");
          out.write("										<a href=\"Progress.do?doctorid=0\"\r\n");
          out.write("											class=\"ms-2   btn btn-outline-danger\">Cancel</a>\r\n");
          out.write("\r\n");
          out.write("									</div>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_html_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_html_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005fform_0026_005fstyleId_005faction.reuse(_jspx_th_html_005fform_005f0);
      _jspx_th_html_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_html_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftext_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:text
    org.apache.struts.taglib.html.TextTag _jspx_th_html_005ftext_005f0 = (org.apache.struts.taglib.html.TextTag) _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleClass_005fstyle_005fproperty_005fdisabled_005fnobody.get(org.apache.struts.taglib.html.TextTag.class);
    boolean _jspx_th_html_005ftext_005f0_reused = false;
    try {
      _jspx_th_html_005ftext_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftext_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(149,12) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setProperty("doctorName");
      // /WEB-INF/jsp/Patient/Progress.jsp(149,12) name = style type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyle("height:40px;");
      // /WEB-INF/jsp/Patient/Progress.jsp(149,12) name = disabled type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setDisabled(true);
      // /WEB-INF/jsp/Patient/Progress.jsp(149,12) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftext_005f0.setStyleClass("form-control");
      int _jspx_eval_html_005ftext_005f0 = _jspx_th_html_005ftext_005f0.doStartTag();
      if (_jspx_th_html_005ftext_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftext_0026_005fstyleClass_005fstyle_005fproperty_005fdisabled_005fnobody.reuse(_jspx_th_html_005ftext_005f0);
      _jspx_th_html_005ftext_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftext_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ftext_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_html_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:textarea
    org.apache.struts.taglib.html.TextareaTag _jspx_th_html_005ftextarea_005f0 = (org.apache.struts.taglib.html.TextareaTag) _005fjspx_005ftagPool_005fhtml_005ftextarea_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.get(org.apache.struts.taglib.html.TextareaTag.class);
    boolean _jspx_th_html_005ftextarea_005f0_reused = false;
    try {
      _jspx_th_html_005ftextarea_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_html_005fform_005f0);
      // /WEB-INF/jsp/Patient/Progress.jsp(155,12) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftextarea_005f0.setProperty("symptoms");
      // /WEB-INF/jsp/Patient/Progress.jsp(155,12) name = styleClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftextarea_005f0.setStyleClass("w-100 h-75 form-control");
      // /WEB-INF/jsp/Patient/Progress.jsp(155,12) name = styleId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005ftextarea_005f0.setStyleId("symptoms");
      int _jspx_eval_html_005ftextarea_005f0 = _jspx_th_html_005ftextarea_005f0.doStartTag();
      if (_jspx_th_html_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005ftextarea_0026_005fstyleId_005fstyleClass_005fproperty_005fnobody.reuse(_jspx_th_html_005ftextarea_005f0);
      _jspx_th_html_005ftextarea_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005ftextarea_005f0, _jsp_getInstanceManager(), _jspx_th_html_005ftextarea_005f0_reused);
    }
    return false;
  }
}
